export const BASE_URL_CATEGORY_ENV_VARIABLE_NAME =
    "VITE_DUMMY_JSON_ENVIRONMENT";


export const ENV_VARIABLE_NAME_APP_NAME =
    "VITE_APP_NAME";

export const ENV_VARIABLE_NAME_REACT_QUERY_STALE_TIME =
    "VITE_REACT_QUERY_STALE_TIME";
